// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Fed",copy:"Kopi\u00e9r",cut:"Klip","delete":"Slet",indent:"Indrykning",insertHorizontalRule:"Vandret linje",insertOrderedList:"Nummereret liste",insertUnorderedList:"Punktliste",italic:"Kursiv",justifyCenter:"Centreret",justifyFull:"Lige margener",justifyLeft:"Venstrejusteret",justifyRight:"H\u00f8jrejusteret",outdent:"Udrykning",paste:"S\u00e6t ind",redo:"Annull\u00e9r Fortryd",removeFormat:"Fjern format",selectAll:"Mark\u00e9r alle",strikethrough:"Gennemstreget",
subscript:"S\u00e6nket skrift",superscript:"H\u00e6vet skrift",underline:"Understreget",undo:"Fortryd",unlink:"Fjern link",createLink:"Opret link",toggleDir:"Skift retning",insertImage:"Inds\u00e6t billede",insertTable:"Inds\u00e6t/redig\u00e9r tabel",toggleTableBorder:"Skift tabelramme",deleteTable:"Slet tabel",tableProp:"Tabelegenskab",htmlToggle:"HTML-kilde",foreColor:"Forgrundsfarve",hiliteColor:"Baggrundsfarve",plainFormatBlock:"Afsnitstypografi",formatBlock:"Afsnitstypografi",fontSize:"Skriftst\u00f8rrelse",
fontName:"Skriftnavn",tabIndent:"Tabulatorindrykning",fullScreen:"Fuld sk\u00e6rm til/fra",viewSource:"Vis HTML-kilde",print:"Udskriv",newPage:"Ny side",systemShortcut:'Funktionen "${0}" kan kun bruges i din browser med en tastaturgenvej. Brug ${1}.',ctrlKey:"Ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"St\u00f8rrelse",fontName:"Skrifttype",formatBlock:"Format",serif:"serif","sans-serif":"sans-serif",monospace:"monospace",cursive:"kursiv",fantasy:"fantasy",
noFormat:"Ingen",p:"Afsnit",h1:"Overskrift",h2:"Underoverskrift",h3:"Underunderoverskrift",pre:"Forudformateret",1:"xx-small",2:"x-small",3:"small",4:"medium",5:"large",6:"x-large",7:"xx-large",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Eksempel",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"S\u00f8g:",findTooltip:"Indtast tekst, du vil s\u00f8ge efter",replaceLabel:"Erstat med:",replaceTooltip:"Indtast tekst, du vil erstatte med",findReplace:"S\u00f8g og erstat",
matchCase:"Forskel p\u00e5 store og sm\u00e5 bogstaver",matchCaseTooltip:"Forskel p\u00e5 store og sm\u00e5 bogstaver",backwards:"Bagl\u00e6ns",backwardsTooltip:"S\u00f8g bagl\u00e6ns i teksten",replaceAllButton:"Erstat alle",replaceAllButtonTooltip:"Erstat i hele teksten",findButton:"S\u00f8g",findButtonTooltip:"Find teksten",replaceButton:"Erstat",replaceButtonTooltip:"Erstat teksten",replaceDialogText:"${0} forekomster erstattet.",eofDialogText:"Sidste forekomst ${0}",eofDialogTextFind:"fundet",
eofDialogTextReplace:"erstattet",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Inds\u00e6t fra Word",instructions:"Inds\u00e6t indholdet fra Word i tekstfeltet nedenfor. Klik p\u00e5 knappen Inds\u00e6t, n\u00e5r du er tilfreds med indholdet. Tryk p\u00e5 knappen Annull\u00e9r for at fortryde inds\u00e6ttelsen.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Inds\u00e6t anker",title:"Egenskaber for anker",anchor:"Navn:",text:"Beskrivelse:",set:"Defin\u00e9r",
cancel:"Annull\u00e9r",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blokanf\u00f8rselstegn",_localized:{}},"widgets/BatchAttributeEditor/setting/nls/strings":{page1:{selectToolHeader:"V\u00e6lg en metode til valg af poster, der skal batch-opdateres.",selectToolDesc:"The widget supports 3 methods to generate a selected set of records to update. You can only choose one of the methods. If you require more than one of these methods, create a new instance of the widget.",selectByShape:"V\u00e6lg efter omr\u00e5de",
shapeTypeSelector:"Choose which tools to allow for selecting features on the map",shapeType:{point:"Punkt",line:"Linje",polyline:"Polylinje",freehandPolyline:"Frih\u00e5ndspolylinje",extent:"Udstr\u00e6kning",polygon:"Polygon",freehandPolygon:"Frih\u00e5ndspolygon"},freehandPolygon:"Frih\u00e5ndspolygon",selectBySpatQuery:"Valgt efter objekt",selectByAttQuery:"V\u00e6lg efter objekter og f\u00e6lles attributv\u00e6rdier",selectByQuery:"V\u00e6lg efter foresp\u00f8rgsel",toolNotSelected:"Please choose a selection method",
noDrawToolSelected:"Please choose at least one drawing tool"},page2:{layersToolHeader:"V\u00e6lg de lag, der skal opdateres, samt eventuelle indstillinger for markeringsv\u00e6rkt\u00f8jer.",layersToolDesc:"The Selection Type you picked from the previous tab will be used to select and update features from a set of layers listed below. If you check more than one layer to update, only the common editable fields will be available to update. Depending on the Selection Type, additional options will be required.",
layerTable:{colUpdate:"Opdat\u00e9r",colLabel:"Lag",colSelectByLayer:"V\u00e6lg efter lag",colSelectByField:"Foresp\u00f8rgselsfelt",colhighlightSymbol:"Fremh\u00e6v symbol"},toggleLayers:"Skift lagenes synlighed ved \u00e5bning og lukning",noEditableLayers:"Ingen redig\u00e9rbare lag",noLayersSelected:"V\u00e6lg et eller flere lag, f\u00f8r du forts\u00e6tter."},page3:{commonFieldsHeader:"V\u00e6lg de felter, der skal batch-opdateres.",commonFieldsDesc:"Only the common editable fields will be shown below.  Please select the fields you wish to update.  If fields sharing the same field name are found across different layers, but have different domains, only one domain can be used.",
noCommonFields:"Ingen almindelige felter",fieldTable:{colEdit:"Redig\u00e9rbar",colName:"Navn",colAlias:"Alias",colAction:"Handlinger"}},tabs:{selection:"Defin\u00e9r udv\u00e6lgelsestype",layers:"Defin\u00e9r lag, der skal opdateres",fields:"Defin\u00e9r felter, der skal opdateres"},errorOnOk:"Please fill out all parameters before saving the configuration",next:"N\u00e6ste",back:"Tilbage",save:"Gem symbol",cancel:"Annull\u00e9r",ok:"OK",symbolPopup:"Symbolv\u00e6lger",editHeaderText:"Tekst, der skal vises \u00f8verst i widget'en",
widgetIntroSelectByArea:"Brug et af v\u00e6rkt\u00f8jerne nedenfor til at oprette et valgt s\u00e6t af objekter, der skal opdateres. Hvis r\u00e6kken er \x3cfont class\x3d'maxRecordInIntro'\x3efremh\u00e6vet\x3c/font\x3e, er det maksimale antal poster overskredet.",widgetIntroSelectByFeature:"Brug v\u00e6rkt\u00f8jet nedenfor til at v\u00e6lge et objekt fra \x3cfont class\x3d'layerInIntro'\x3e${0}\x3c/font\x3e laget. Dette objekt vil blive brugt til at v\u00e6lge og opdatere alle objekter, der er gennemsk\u00e5ret. Hvis r\u00e6kken er \x3cfont class\x3d'maxRecordInIntro'\x3efremh\u00e6vet\x3c/font\x3e, er det maksimale antal poster overskredet.",
widgetIntroSelectByFeatureQuery:"Brug v\u00e6rkt\u00f8jet nedenfor til at v\u00e6lge et objekt fra \x3cfont class\x3d'layerInIntro'\x3e${0}\x3c/font\x3e . Dette objekts \x3cfont class\x3d'layerInIntro'\x3e${1}\x3c/font\x3e attribut vil blive brugt til at sende foresp\u00f8rgsler vedr\u00f8rende lagene nedenfor og opdatere de resulterende objekter. Hvis r\u00e6kken er \x3cfont class\x3d'maxRecordInIntro'\x3efremh\u00e6vet\x3c/font\x3e, er det maksimale antal poster overskredet.",widgetIntroSelectByQuery:"Angiv en v\u00e6rdi for at oprette et valgt s\u00e6t. Hvis r\u00e6kken er \x3cfont class\x3d'maxRecordInIntro'\x3efremh\u00e6vet\x3c/font\x3e, er det maksimale antal poster overskredet.",
_localized:{}}});