// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Aldin",copy:"Copiere",cut:"T\u0103iere","delete":"\u015etergere",indent:"Mic\u015forare indent",insertHorizontalRule:"Linie delimitatoare",insertOrderedList:"List\u0103 numerotat\u0103",insertUnorderedList:"List\u0103 cu marcator",italic:"Cursiv",justifyCenter:"Aliniere centru",justifyFull:"Aliniere st\u00e2nga-dreapta",justifyLeft:"Aliniere st\u00e2nga",justifyRight:"Aliniere dreapta",outdent:"M\u0103rire indent",paste:"Lipire",redo:"Refacere ac\u0163iune",
removeFormat:"\u00cenl\u0103turare format",selectAll:"Selecteaz\u0103 tot",strikethrough:"T\u0103iere text cu o linie",subscript:"Scriere indice inferior",superscript:"Scriere indice superior",underline:"Subliniere",undo:"Anulare ac\u0163iune",unlink:"\u00cenl\u0103turare leg\u0103tur\u0103",createLink:"Creare leg\u0103tur\u0103",toggleDir:"Comutare direc\u0163ie",insertImage:"Inserare imagine",insertTable:"Inserare/Editare tabel\u0103",toggleTableBorder:"Comutare bordur\u0103 tabel\u0103",deleteTable:"\u015etergere tabel\u0103",
tableProp:"Proprietate tabel\u0103",htmlToggle:"Surs\u0103 HTML",foreColor:"Culoare de prim-plan",hiliteColor:"Culoare de fundal",plainFormatBlock:"Stil paragraf",formatBlock:"Stil paragraf",fontSize:"Dimensiune font",fontName:"Nume font",tabIndent:"Indentare Tab",fullScreen:"Comutare ecran complet",viewSource:"Vizualizara surs\u0103 HTML",print:"Tip\u0103rire",newPage:"Pagin\u0103 nou\u0103",systemShortcut:'Ac\u0163iunea "${0}" este disponibil\u0103 \u00een browser doar utiliz\u00e2nd o comand\u0103 rapid\u0103 de la tastatur\u0103. Utiliza\u0163i ${1}.',
ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"M\u0103rime",fontName:"Font",formatBlock:"Format",serif:"serif","sans-serif":"sans-serif",monospace:"monospace",cursive:"cursive",fantasy:"fantasy",noFormat:"Nimic",p:"Paragraf",h1:"Titlu",h2:"Subtitlu",h3:"Sub-subtitlu",pre:"Preformatat",1:"xxs (xx-small)",2:"xs (x-small)",3:"s (small)",4:"m (medium)",5:"l (large)",6:"xl (x-large)",7:"xxl (xx-large)",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Previzualizare",
_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"G\u0103sire:",findTooltip:"Introduce\u0163i textul de g\u0103sit",replaceLabel:"\u00cenlocuire cu:",replaceTooltip:"Introduce\u0163i textul cu care s\u0103 \u00eenlocui\u0163i",findReplace:"G\u0103sire \u015fi \u00eenlocuire",matchCase:"Potrivire majuscule",matchCaseTooltip:"Potrivire majuscule",backwards:"\u00cenapoi",backwardsTooltip:"C\u0103utare \u00eenapoi pentru text",replaceAllButton:"\u00cenlocuire tot",replaceAllButtonTooltip:"\u00cenlocui\u0163i tot textul",
findButton:"G\u0103sire",findButtonTooltip:"G\u0103si\u0163i text",replaceButton:"\u00cenlocuire",replaceButtonTooltip:"\u00cenlocui\u0163i text",replaceDialogText:"Au fost \u00eenlocuite ${0} apari\u0163ii.",eofDialogText:"Ultima apari\u0163ie ${0}",eofDialogTextFind:"g\u0103sit",eofDialogTextReplace:"\u00eenlocuit",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Lipire din Word",instructions:"Lipi\u0163i con\u0163inutul din Word \u00een caseta text de mai jos. C\u00e2nd sunte\u0163i satisf\u0103cut cu con\u0163inutul, pentru a insera, ap\u0103sa\u0163i butonul Lipire. Pentru a renun\u0163a la inserarea textului, ap\u0103sa\u0163i butonul Anulare.",
_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Inserare ancor\u0103",title:"Propriet\u0103\u0163i ancor\u0103",anchor:"Nume:",text:"Descriere:",set:"Setare",cancel:"Anulare",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Bloc citat",_localized:{}},"widgets/BatchAttributeEditor/setting/nls/strings":{page1:{selectToolHeader:"Alege\u0163i o metod\u0103 pentru a alege \u00eenregistr\u0103rile pentru actualizarea \u00een mas\u0103.",selectToolDesc:"The widget supports 3 methods to generate a selected set of records to update. You can only choose one of the methods. If you require more than one of these methods, create a new instance of the widget.",
selectByShape:"Selectare dup\u0103 zon\u0103",shapeTypeSelector:"Choose which tools to allow for selecting features on the map",shapeType:{point:"Punct",line:"Linie",polyline:"Linie poligonal\u0103",freehandPolyline:"Linie poligonal\u0103 trasat\u0103 manual",extent:"Extindere",polygon:"Poligon",freehandPolygon:"Poligon trasat manual"},freehandPolygon:"Poligon trasat manual",selectBySpatQuery:"Selectare dup\u0103 obiect spa\u0163ial",selectByAttQuery:"Selecta\u021bi \u00een func\u021bie de valorile obiectului spa\u021bial \u0219i ale atributului comun",
selectByQuery:"Selectare dup\u0103 interogare",toolNotSelected:"Please choose a selection method",noDrawToolSelected:"Please choose at least one drawing tool"},page2:{layersToolHeader:"Selecta\u0163i straturile tematice care vor fi actualizate \u015fi op\u0163iunile instrumentelor de selec\u0163ie, dac\u0103 exist\u0103.",layersToolDesc:"The Selection Type you picked from the previous tab will be used to select and update features from a set of layers listed below. If you check more than one layer to update, only the common editable fields will be available to update. Depending on the Selection Type, additional options will be required.",
layerTable:{colUpdate:"Actualizare",colLabel:"Strat tematic",colSelectByLayer:"Selectare dup\u0103 strat tematic",colSelectByField:"C\u00e2mp interogare",colhighlightSymbol:"Eviden\u0163iere simbol"},toggleLayers:"Comutare vizibilitate straturi tematice la deschidere \u0219i \u00eenchidere",noEditableLayers:"Niciun strat tematic editabil",noLayersSelected:"Selecta\u0163i unul sau mai multe straturi tematice \u00eenainte de a continua."},page3:{commonFieldsHeader:"Selecta\u0163i c\u00e2mpurile care vor fi actualizate \u00een mas\u0103.",
commonFieldsDesc:"Only the common editable fields will be shown below.  Please select the fields you wish to update.  If fields sharing the same field name are found across different layers, but have different domains, only one domain can be used.",noCommonFields:"Niciun c\u00e2mp comun",fieldTable:{colEdit:"Editabil",colName:"Nume",colAlias:"Pseudonim",colAction:"Ac\u0163iuni"}},tabs:{selection:"Definire tip selec\u0163ie",layers:"Definire straturi tematice care vor fi actualizate",fields:"Definire c\u00e2mpuri care vor fi actualizate"},
errorOnOk:"Please fill out all parameters before saving the configuration",next:"\u00cenainte",back:"\u00cenapoi",save:"Salvare simbol",cancel:"Anulare",ok:"OK",symbolPopup:"Selector simbol",editHeaderText:"Text care va fi afi\u0219at \u00een partea de sus a widgetului",widgetIntroSelectByArea:"Utiliza\u021bi unul dintre instrumentele de mai jos pentru a crea un set selectat de obiecte spa\u021biale de actualizat. Dac\u0103 r\u00e2ndul este \x3cfont class\x3d'maxRecordInIntro'\x3eeviden\u021biat\x3c/font\x3e, a fost dep\u0103\u0219it num\u0103rul maxim de \u00eenregistr\u0103ri.",
widgetIntroSelectByFeature:"Utiliza\u021bi instrumentul de mai jos pentru a selecta un obiect spa\u021bial din stratul tematic \x3cfont class\x3d'layerInIntro'\x3e${0}\x3c/font\x3e. Acest obiect spa\u021bial va fi utilizat pentru a selecta \u0219i actualiza toate obiectele spa\u021biale cu care se intersecteaz\u0103. Dac\u0103 r\u00e2ndul este \x3cfont class\x3d'maxRecordInIntro'\x3eeviden\u021biat\x3c/font\x3e, a fost dep\u0103\u0219it num\u0103rul maxim de \u00eenregistr\u0103ri.",widgetIntroSelectByFeatureQuery:"Utiliza\u021bi instrumentul de mai jos pentru a selecta un obiect spa\u021bial din \x3cfont class\x3d'layerInIntro'\x3e${0}\x3c/font\x3e. Atributul \x3cfont class\x3d'layerInIntro'\x3e${1}\x3c/font\x3e al acestui obiect spa\u021bial va fi utilizat pentru a interoga straturile tematice de mai jos \u0219i pentru a actualiza obiectele spa\u021biale care rezult\u0103. Dac\u0103 r\u00e2ndul este \x3cfont class\x3d'maxRecordInIntro'\x3eeviden\u021biat\x3c/font\x3e, a fost dep\u0103\u0219it num\u0103rul maxim de \u00eenregistr\u0103ri.",
widgetIntroSelectByQuery:"Introduce\u021bi o valoare pentru a crea un set de selec\u021bie. Dac\u0103 r\u00e2ndul este \x3cfont class\x3d'maxRecordInIntro'\x3eeviden\u021biat\x3c/font\x3e, a fost dep\u0103\u0219it num\u0103rul maxim de \u00eenregistr\u0103ri.",_localized:{}}});