// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Pogrubienie",copy:"Kopiuj",cut:"Wytnij","delete":"Usu\u0144",indent:"Wci\u0119cie",insertHorizontalRule:"Linia pozioma",insertOrderedList:"Lista numerowana",insertUnorderedList:"Lista wypunktowana",italic:"Kursywa",justifyCenter:"Wyr\u00f3wnaj do \u015brodka",justifyFull:"Wyr\u00f3wnaj do lewej i prawej",justifyLeft:"Wyr\u00f3wnaj do lewej",justifyRight:"Wyr\u00f3wnaj do prawej",outdent:"Usu\u0144 wci\u0119cie",paste:"Wklej",redo:"Pon\u00f3w",removeFormat:"Usu\u0144 formatowanie",
selectAll:"Wybierz wszystko",strikethrough:"Przekre\u015blenie",subscript:"Indeks dolny",superscript:"Indeks g\u00f3rny",underline:"Podkre\u015blenie",undo:"Cofnij",unlink:"Usu\u0144 odsy\u0142acz",createLink:"Utw\u00f3rz odsy\u0142acz",toggleDir:"Prze\u0142\u0105cz kierunek",insertImage:"Wstaw obraz",insertTable:"Wstaw/edytuj tabel\u0119",toggleTableBorder:"Prze\u0142\u0105cz ramk\u0119 tabeli",deleteTable:"Usu\u0144 tabel\u0119",tableProp:"W\u0142a\u015bciwo\u015b\u0107 tabeli",htmlToggle:"\u0179r\u00f3d\u0142o HTML",
foreColor:"Kolor pierwszego planu",hiliteColor:"Kolor t\u0142a",plainFormatBlock:"Styl akapitu",formatBlock:"Styl akapitu",fontSize:"Wielko\u015b\u0107 czcionki",fontName:"Nazwa czcionki",tabIndent:"Wci\u0119cie o tabulator",fullScreen:"Prze\u0142\u0105cz pe\u0142ny ekran",viewSource:"Wy\u015bwietl kod \u017ar\u00f3d\u0142owy HTML",print:"Drukuj",newPage:"Nowa strona",systemShortcut:"Dzia\u0142anie ${0} jest dost\u0119pne w tej przegl\u0105darce wy\u0142\u0105cznie przy u\u017cyciu skr\u00f3tu klawiaturowego. Nale\u017cy u\u017cy\u0107 klawiszy ${1}.",
ctrlKey:"Ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Rozmiar",fontName:"Czcionka",formatBlock:"Format",serif:"szeryfowa","sans-serif":"bezszeryfowa",monospace:"czcionka o sta\u0142ej szeroko\u015bci",cursive:"kursywa",fantasy:"fantazyjna",noFormat:"Brak",p:"Akapit",h1:"Nag\u0142\u00f3wek",h2:"Nag\u0142\u00f3wek 2-go poziomu",h3:"Nag\u0142\u00f3wek 3-go poziomu",pre:"Wst\u0119pnie sformatowane",1:"najmniejsza",2:"mniejsza",3:"ma\u0142a",4:"\u015brednia",
5:"du\u017ce",6:"wi\u0119ksza",7:"najwi\u0119ksza",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Podgl\u0105d",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Znajd\u017a:",findTooltip:"Wprowad\u017a szukany tekst",replaceLabel:"Zast\u0105p przez:",replaceTooltip:"Wprowad\u017a tekst zast\u0119puj\u0105cy",findReplace:"Znajd\u017a i zast\u0105p",matchCase:"Uwzgl\u0119dnij wielko\u015b\u0107 liter",matchCaseTooltip:"Uwzgl\u0119dnij wielko\u015b\u0107 liter",backwards:"Do ty\u0142u",
backwardsTooltip:"Wyszukaj tekst wstecz",replaceAllButton:"Zast\u0105p wszystko",replaceAllButtonTooltip:"Zast\u0105p ca\u0142y tekst",findButton:"Znajd\u017a",findButtonTooltip:"Znajd\u017a tekst",replaceButton:"Zast\u0105p",replaceButtonTooltip:"Zast\u0105p tekst",replaceDialogText:"Zast\u0105pione wyst\u0105pienia: ${0}.",eofDialogText:"Ostatnie wyst\u0105pienie: ${0}",eofDialogTextFind:"znaleziono",eofDialogTextReplace:"zast\u0105pione",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Wklej z programu Word",
instructions:"Wklej tekst z programu Word do poni\u017cszego pola tekstowego. Po uzyskaniu odpowiedniej tre\u015bci do wstawienia kliknij przycisk Wklej. Aby przerwa\u0107 wstawianie tre\u015bci, kliknij przycisk Anuluj.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Wstaw zakotwiczenie",title:"W\u0142a\u015bciwo\u015bci zakotwiczenia",anchor:"Nazwa:",text:"Opis:",set:"Ustaw",cancel:"Anuluj",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Cytat blokowy",_localized:{}},
"widgets/BatchAttributeEditor/setting/nls/strings":{page1:{selectToolHeader:"Okre\u015bl metod\u0119 wyboru rekord\u00f3w do aktualizowania wsadowego.",selectToolDesc:"The widget supports 3 methods to generate a selected set of records to update. You can only choose one of the methods. If you require more than one of these methods, create a new instance of the widget.",selectByShape:"Wybierz wed\u0142ug obszaru",shapeTypeSelector:"Choose which tools to allow for selecting features on the map",shapeType:{point:"Punkt",
line:"Linia",polyline:"Polilinia",freehandPolyline:"Polilinia odr\u0119czna",extent:"Zasi\u0119g",polygon:"Poligon",freehandPolygon:"Poligon odr\u0119czny"},freehandPolygon:"Poligon odr\u0119czny",selectBySpatQuery:"Wybierz wed\u0142ug obiektu",selectByAttQuery:"Wybierz wed\u0142ug warto\u015bci obiektu i udost\u0119pnionego atrybutu",selectByQuery:"Wybierz wed\u0142ug zapytania",toolNotSelected:"Please choose a selection method",noDrawToolSelected:"Please choose at least one drawing tool"},page2:{layersToolHeader:"Wybierz warstwy do uaktualnienia i opcje narz\u0119dzi wyboru (je\u017celi s\u0105).",
layersToolDesc:"The Selection Type you picked from the previous tab will be used to select and update features from a set of layers listed below. If you check more than one layer to update, only the common editable fields will be available to update. Depending on the Selection Type, additional options will be required.",layerTable:{colUpdate:"Zmie\u0144",colLabel:"Warstwa",colSelectByLayer:"Wybierz  wed\u0142ug warstwy",colSelectByField:"Pole zapytania",colhighlightSymbol:"Symbol pod\u015bwietlenia"},
toggleLayers:"Prze\u0142\u0105czaj widzialno\u015b\u0107 warstw na otwarte/zamkni\u0119te",noEditableLayers:"Brak edytowalnych warstw",noLayersSelected:"Wybierz co najmniej jedn\u0105 warstw\u0119 przed kontynuacj\u0105."},page3:{commonFieldsHeader:"Wybierz pola do aktualizacji wsadowej.",commonFieldsDesc:"Only the common editable fields will be shown below.  Please select the fields you wish to update.  If fields sharing the same field name are found across different layers, but have different domains, only one domain can be used.",
noCommonFields:"Brak wsp\u00f3lnych p\u00f3l",fieldTable:{colEdit:"Edytowalne",colName:"Nazwa",colAlias:"Alias",colAction:"Dzia\u0142ania"}},tabs:{selection:"Zdefiniuj rodzaj wyboru",layers:"Zdefiniuj warstwy do aktualizacji",fields:"Zdefiniuj pola do aktualizacji"},errorOnOk:"Please fill out all parameters before saving the configuration",next:"Dalej",back:"Powr\u00f3t",save:"Zapisz symbol",cancel:"Anuluj",ok:"OK",symbolPopup:"Wyb\u00f3r symbolu",editHeaderText:"Tekst do wy\u015bwietlenia w g\u00f3rnej cz\u0119\u015bci wid\u017cetu",
widgetIntroSelectByArea:"U\u017cyj jednego z poni\u017cszych narz\u0119dzi, aby utworzy\u0107 wybrany zestaw obiekt\u00f3w do zaktualizowania.  Je\u015bli wiersz zosta\u0142 \x3cfont class\x3d'maxRecordInIntro'\x3ewyr\u00f3\u017cniony\x3c/font\x3e, przekroczono maksymaln\u0105 liczb\u0119 rekord\u00f3w.",widgetIntroSelectByFeature:"U\u017cyj poni\u017cszego narz\u0119dzia, aby wybra\u0107 obiekt z warstwy \x3cfont class\x3d'layerInIntro'\x3e${0}\x3c/font\x3e. Ten obiekt zostanie u\u017cyty do wybrania i zaktualizowania wszystkich przecinaj\u0105cych si\u0119 z nim obiekt\u00f3w. Je\u015bli wiersz zosta\u0142 \x3cfont class\x3d'maxRecordInIntro'\x3ewyr\u00f3\u017cniony\x3c/font\x3e, przekroczono maksymaln\u0105 liczb\u0119 rekord\u00f3w.",
widgetIntroSelectByFeatureQuery:"U\u017cyj poni\u017cszego narz\u0119dzia, aby wybra\u0107 obiekt z warstwy \x3cfont class\x3d'layerInIntro'\x3e${0}\x3c/font\x3e. Atrybut \x3cfont class\x3d'layerInIntro'\x3e${1}\x3c/font\x3e tego obiektu b\u0119dzie u\u017cywany do tworzenia zapyta\u0144 dotycz\u0105cych poni\u017cszych warstw i aktualizowania obiekt\u00f3w wynikowych.  Je\u015bli wiersz zosta\u0142 \x3cfont class\x3d'maxRecordInIntro'\x3ewyr\u00f3\u017cniony\x3c/font\x3e, przekroczono maksymaln\u0105 liczb\u0119 rekord\u00f3w.",
widgetIntroSelectByQuery:"Wprowad\u017a warto\u015b\u0107, aby utworzy\u0107 zestaw wybranych element\u00f3w.  Je\u015bli wiersz zosta\u0142 \x3cfont class\x3d'maxRecordInIntro'\x3ewyr\u00f3\u017cniony\x3c/font\x3e, przekroczono maksymaln\u0105 liczb\u0119 rekord\u00f3w.",_localized:{}}});