// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Fett",copy:"Kopieren",cut:"Ausschneiden","delete":"L\u00f6schen",indent:"Einr\u00fccken",insertHorizontalRule:"Horizontaler Strich",insertOrderedList:"Nummerierung",insertUnorderedList:"Aufz\u00e4hlungszeichen",italic:"Kursiv",justifyCenter:"Zentriert",justifyFull:"Blocksatz",justifyLeft:"Linksb\u00fcndig",justifyRight:"Rechtsb\u00fcndig",outdent:"Ausr\u00fccken",paste:"Einf\u00fcgen",redo:"Wiederholen",removeFormat:"Formatierung entfernen",selectAll:"Alles ausw\u00e4hlen",
strikethrough:"Durchgestrichen",subscript:"Tiefgestellt",superscript:"Hochgestellt",underline:"Unterstrichen",undo:"R\u00fcckg\u00e4ngig",unlink:"Link entfernen",createLink:"Link erstellen",toggleDir:"Richtung wechseln",insertImage:"Grafik einf\u00fcgen",insertTable:"Tabelle einf\u00fcgen/bearbeiten",toggleTableBorder:"Tabellenumrandung ein-/ausschalten",deleteTable:"Tabelle l\u00f6schen",tableProp:"Tabelleneigenschaft",htmlToggle:"HTML-Quelltext",foreColor:"Vordergrundfarbe",hiliteColor:"Hintergrundfarbe",
plainFormatBlock:"Absatzstil",formatBlock:"Absatzstil",fontSize:"Schriftgr\u00f6\u00dfe",fontName:"Schriftartname",tabIndent:"Registerkarteneinr\u00fcckung",fullScreen:"Gesamtanzeige",viewSource:"HTML-Quelle",print:"Drucken",newPage:"Neue Seite",systemShortcut:'Die Aktion "${0}" ist nur \u00fcber einen Direktaufruf in Ihrem Browser verf\u00fcgbar. Verwenden Sie ${1}.',ctrlKey:"Strg+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Gr\u00f6\u00dfe",fontName:"Schriftart",
formatBlock:"Format",serif:"Serife","sans-serif":"Serifenlos",monospace:"Monospaceschrift",cursive:"Kursiv",fantasy:"Fantasie",noFormat:"Keine Angabe",p:"Absatz",h1:"\u00dcberschrift",h2:"Unter\u00fcberschrift",h3:"Unterunter\u00fcberschrift",pre:"Vorformatiert",1:"XXS",2:"XS",3:"S",4:"M",5:"L",6:"XL",7:"XXL",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Vorschau",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Suchen:",findTooltip:"Text zum Suchen eingeben",replaceLabel:"Ersetzen durch:",
replaceTooltip:"Text zum Ersetzen eingeben",findReplace:"Suchen und ersetzen",matchCase:"Gro\u00df- und Kleinschreibung abgleichen",matchCaseTooltip:"Gro\u00df- und Kleinschreibung abgleichen",backwards:"Zur\u00fcck",backwardsTooltip:"R\u00fcckw\u00e4rts nach Text suchen",replaceAllButton:"Global ersetzen",replaceAllButtonTooltip:"Gesamten Text ersetzen",findButton:"Suchen",findButtonTooltip:"Text suchen",replaceButton:"Ersetzen",replaceButtonTooltip:"Text ersetzen",replaceDialogText:"${0} Vorkommen ersetzt.",
eofDialogText:"Letztes Vorkommen ${0}",eofDialogTextFind:"gefunden",eofDialogTextReplace:"ersetzt",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Aus Word einf\u00fcgen",instructions:"F\u00fcgt den Inhalt aus Word in das Textfeld unten ein. Wenn Sie mit dem einzuf\u00fcgenden Inhalt zufrieden sind, klicken Sie auf die Schaltfl\u00e4che zum Einf\u00fcgen. Um das Einf\u00fcgen von Text abzubrechen, klicken Sie auf die Schaltfl\u00e4che zum Abbrechen. ",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Anker einf\u00fcgen",
title:"Eigenschaften des Ankers",anchor:"Name:",text:"Beschreibung:",set:"Festlegen",cancel:"Abbrechen",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blockzitat",_localized:{}},"widgets/BatchAttributeEditor/setting/nls/strings":{page1:{selectToolHeader:"Legen Sie eine Methode zum Ausw\u00e4hlen von Datens\u00e4tzen f\u00fcr die Batch-Aktualisierung fest.",selectToolDesc:"The widget supports 3 methods to generate a selected set of records to update. You can only choose one of the methods. If you require more than one of these methods, create a new instance of the widget.",
selectByShape:"Nach Bereich ausw\u00e4hlen",shapeTypeSelector:"Choose which tools to allow for selecting features on the map",shapeType:{point:"Punkt",line:"Linie",polyline:"Polylinie",freehandPolyline:"Freihand-Polylinie",extent:"Ausdehnung",polygon:"Polygon",freehandPolygon:"Freihand-Polygon"},freehandPolygon:"Freihand-Polygon",selectBySpatQuery:"Nach Feature ausw\u00e4hlen",selectByAttQuery:"Nach Feature und gemeinsamen Attributwerten ausw\u00e4hlen",selectByQuery:"Nach Abfrage ausw\u00e4hlen",
toolNotSelected:"Please choose a selection method",noDrawToolSelected:"Please choose at least one drawing tool"},page2:{layersToolHeader:"W\u00e4hlen Sie die zu aktualisierenden Layer und die Auswahlwerkzeugoptionen aus, falls vorhanden.",layersToolDesc:"The Selection Type you picked from the previous tab will be used to select and update features from a set of layers listed below. If you check more than one layer to update, only the common editable fields will be available to update. Depending on the Selection Type, additional options will be required.",
layerTable:{colUpdate:"Aktualisieren",colLabel:"Layer",colSelectByLayer:"Nach Layer ausw\u00e4hlen",colSelectByField:"Abfrage-Feld",colhighlightSymbol:"Hervorhebungssymbol"},toggleLayers:"Layer-Sichtbarkeit beim \u00d6ffnen und Schlie\u00dfen umschalten",noEditableLayers:"Keine editierbaren Layer",noLayersSelected:"W\u00e4hlen Sie mindestens einen Layer aus, bevor Sie den Vorgang fortsetzen."},page3:{commonFieldsHeader:"W\u00e4hlen Sie die Felder f\u00fcr die Batch-Aktualisierung aus.",commonFieldsDesc:"Only the common editable fields will be shown below.  Please select the fields you wish to update.  If fields sharing the same field name are found across different layers, but have different domains, only one domain can be used.",
noCommonFields:"Keine allgemeinen Felder",fieldTable:{colEdit:"Editierbar",colName:"Name",colAlias:"Alias",colAction:"Aktionen"}},tabs:{selection:"Auswahltyp definieren",layers:"Zu aktualisierende(n) Layer definieren",fields:"Zu aktualisierende(s) Feld(er) definieren"},errorOnOk:"Please fill out all parameters before saving the configuration",next:"Weiter",back:"Zur\u00fcck",save:"Symbol speichern",cancel:"Abbrechen",ok:"OK",symbolPopup:"Symbolauswahl",editHeaderText:"Text, der oben im Widget angezeigt werden soll",
widgetIntroSelectByArea:"Verwenden Sie eines der nachfolgenden Werkzeuge, um eine ausgew\u00e4hlte Reihe von Features zu erstellen, die aktualisiert werden sollen. Wenn die Zeile \x3cfont class\x3d'maxRecordInIntro'\x3ehervorgehoben\x3c/font\x3e ist, wurde die maximale Anzahl von Datens\u00e4tzen \u00fcberschritten.",widgetIntroSelectByFeature:"Verwenden Sie das nachfolgende Werkzeug, um ein Feature aus dem Layer \x3cfont class\x3d'layerInIntro'\x3e${0}\x3c/font\x3e auszuw\u00e4hlen. Dieses Feature dient zum Ausw\u00e4hlen und Aktualisieren aller \u00fcberschneidenden Features. Wenn die Zeile \x3cfont class\x3d'maxRecordInIntro'\x3ehervorgehoben\x3c/font\x3e ist, wurde die maximale Anzahl von Datens\u00e4tzen \u00fcberschritten.",
widgetIntroSelectByFeatureQuery:"Verwenden Sie das nachfolgende Werkzeug, um ein Feature aus \x3cfont class\x3d'layerInIntro'\x3e${0}\x3c/font\x3e auszuw\u00e4hlen.  Das \x3cfont class\x3d'layerInIntro'\x3e${1}\x3c/font\x3e-Attribut dieses Features wird verwendet, um die nachfolgenden Layer abzufragen und die resultierenden Features zu aktualisieren.  Wenn die Zeile \x3cfont class\x3d'maxRecordInIntro'\x3ehervorgehoben\x3c/font\x3e ist, wurde die maximale Anzahl von Datens\u00e4tzen \u00fcberschritten.",
widgetIntroSelectByQuery:"Geben Sie einen Wert ein, um einen Auswahlsatz zu erstellen.  Wenn die Zeile \x3cfont class\x3d'maxRecordInIntro'\x3ehervorgehoben\x3c/font\x3e ist, wurde die maximale Anzahl von Datens\u00e4tzen \u00fcberschritten.",_localized:{}}});