// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Fet",copy:"Kopier",cut:"Klipp ut","delete":"Slett",indent:"Innrykk",insertHorizontalRule:"Vannrett strek",insertOrderedList:"Nummerert liste",insertUnorderedList:"Punktliste",italic:"Kursiv",justifyCenter:"Midtstill",justifyFull:"Juster",justifyLeft:"Venstrejuster",justifyRight:"H\u00f8yrejuster",outdent:"Fjern innrykk",paste:"Lim inn",redo:"Gj\u00f8r om",removeFormat:"Fjern format",selectAll:"Velg alle",strikethrough:"Gjennomstreking",subscript:"Senket skrift",
superscript:"Hevet skrift",underline:"Understreking",undo:"Angre",unlink:"Fjern kobling",createLink:"Opprett kobling",toggleDir:"Bytt retning",insertImage:"Sett inn bilde",insertTable:"Sett inn/rediger tabell",toggleTableBorder:"Bytt tabellkant",deleteTable:"Slett tabell",tableProp:"Tabellegenskap",htmlToggle:"HTML-kilde",foreColor:"Forgrunnsfarge",hiliteColor:"Bakgrunnsfarge",plainFormatBlock:"Avsnittsstil",formatBlock:"Avsnittsstil",fontSize:"Skriftst\u00f8rrelse",fontName:"Skriftnavn",tabIndent:"Tabulatorinnrykk",
fullScreen:"Sl\u00e5 p\u00e5/av full skjerm",viewSource:"Vis HTML-kilde",print:"Skriv ut",newPage:"Ny side",systemShortcut:'Handlingen "${0}" er bare tilgjengelig i nettleseren ved hjelp av en tastatursnarvei. Bruk ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"St\u00f8rrelse",fontName:"Skrift",formatBlock:"Format",serif:"serif","sans-serif":"sans-serif",monospace:"monospace",cursive:"kursiv",fantasy:"fantasi",noFormat:"Ingen",p:"Avsnitt",
h1:"Overskrift",h2:"Undertittel",h3:"Under-undertittel",pre:"Forh\u00e5ndsformatert",1:"xx-liten",2:"x-liten",3:"liten",4:"middels",5:"stor",6:"x-stor",7:"xx-stor",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Forh\u00e5ndsvis",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"S\u00f8k:",findTooltip:"Skriv inn teksten du vil s\u00f8ke etter",replaceLabel:"Erstatt med:",replaceTooltip:"Skriv inn teksten du vil erstatte med",findReplace:"S\u00f8k og erstatt",matchCase:"Skill mellom store og sm\u00e5 bokstaver",
matchCaseTooltip:"Skill mellom store og sm\u00e5 bokstaver",backwards:"Bakover",backwardsTooltip:"S\u00f8k bakover etter tekst",replaceAllButton:"Erstatt alle",replaceAllButtonTooltip:"Erstatt all tekst",findButton:"S\u00f8k",findButtonTooltip:"S\u00f8k etter teksten",replaceButton:"Erstatt",replaceButtonTooltip:"Erstatt teksten",replaceDialogText:"Erstattet ${0} forekomster.",eofDialogText:"Siste forekomst ${0}",eofDialogTextFind:"funnet",eofDialogTextReplace:"erstattet",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Lim inn fra Word",
instructions:"Lim inn innhold fra Word til tekstboksen nedenfor. N\u00e5r du er forn\u00f8yd med innholdet du skal sette inn, trykker du p\u00e5 innlimingsknappen. Hvis du vil avbryte innsettingen av teksten, trykker du p\u00e5 avbruddsknappen.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Sett inn anker",title:"Ankeregenskaper",anchor:"Navn:",text:"Beskrivelse:",set:"Definer",cancel:"Avbryt",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blokksitat",_localized:{}},
"widgets/BatchAttributeEditor/setting/nls/strings":{page1:{selectToolHeader:"Velg en metode for \u00e5 velge poster til satsvis oppdatering.",selectToolDesc:"The widget supports 3 methods to generate a selected set of records to update. You can only choose one of the methods. If you require more than one of these methods, create a new instance of the widget.",selectByShape:"Velg etter omr\u00e5de",shapeTypeSelector:"Choose which tools to allow for selecting features on the map",shapeType:{point:"Punkt",
line:"Linje",polyline:"Polylinje",freehandPolyline:"Frih\u00e5ndspolylinje",extent:"Utstrekning",polygon:"Polygon",freehandPolygon:"Frih\u00e5ndspolygon"},freehandPolygon:"Frih\u00e5ndspolygon",selectBySpatQuery:"Velg etter geoobjekt",selectByAttQuery:"Velg etter geoobjekt og delte attributtverdier",selectByQuery:"Velg etter sp\u00f8rring",toolNotSelected:"Please choose a selection method",noDrawToolSelected:"Please choose at least one drawing tool"},page2:{layersToolHeader:"Velg lagene som skal oppdateres og eventuelle alternativer for utvalgsverkt\u00f8yene.",
layersToolDesc:"The Selection Type you picked from the previous tab will be used to select and update features from a set of layers listed below. If you check more than one layer to update, only the common editable fields will be available to update. Depending on the Selection Type, additional options will be required.",layerTable:{colUpdate:"Oppdatere",colLabel:"Lag",colSelectByLayer:"Velg etter lag",colSelectByField:"Sp\u00f8rringsfelt",colhighlightSymbol:"Uthevingssymbol"},toggleLayers:"Veksle lagsynlighet ved \u00e5pning og lukking",
noEditableLayers:"Ingen redigerbare lag",noLayersSelected:"Velg et eller flere lag f\u00f8r du fortsetter."},page3:{commonFieldsHeader:"Velg feltet for satsvis oppdatering.",commonFieldsDesc:"Only the common editable fields will be shown below.  Please select the fields you wish to update.  If fields sharing the same field name are found across different layers, but have different domains, only one domain can be used.",noCommonFields:"Ingen fellesfelt",fieldTable:{colEdit:"Redigerbar",colName:"Navn",
colAlias:"Alias",colAction:"Handlinger"}},tabs:{selection:"Definer utvalgstype",layers:"Definer laget/lagene som skal oppdateres",fields:"Definer feltet/feltene som skal oppdateres"},errorOnOk:"Please fill out all parameters before saving the configuration",next:"Neste",back:"Tilbake",save:"Lagre-symbol",cancel:"Avbryt",ok:"OK",symbolPopup:"Symbolvelger",editHeaderText:"Tekst som skal vises \u00f8verst i miniprogrammet",widgetIntroSelectByArea:"Bruk et av verkt\u00f8yene nedenfor til \u00e5 opprette et utvalgt sett med geoobjekter som skal oppdateres. Hvis raden er \x3cfont class\x3d'maxRecordInIntro'\x3euthevet\x3c/font\x3e, er maksimum antall poster overskredet.",
widgetIntroSelectByFeature:"Bruk verkt\u00f8yet nedenfor til \u00e5 velge et geoobjekt fra laget \x3cfont class\x3d'layerInIntro'\x3e${0}\x3c/font\x3e. Dette geoobjektet brukes til \u00e5 velge og oppdatere alle kryssende geoobjekter. Hvis raden er \x3cfont class\x3d'maxRecordInIntro'\x3euthevet\x3c/font\x3e, er maksimum antall poster overskredet.",widgetIntroSelectByFeatureQuery:"Bruk verkt\u00f8yet nedenfor til \u00e5 velge et geoobjekt fra \x3cfont class\x3d'layerInIntro'\x3e${0}\x3c/font\x3e-laget.   Geoobjektets \x3cfont class\x3d'layerInIntro'\x3e${1}\x3c/font\x3e-attributt brukes til \u00e5 sp\u00f8rre lagene nedenfor og oppdatere de resulterende geoobjektene. Hvis raden er \x3cfont class\x3d'maxRecordInIntro'\x3euthevet\x3c/font\x3e, er maksimum antall poster overskredet.",
widgetIntroSelectByQuery:"Skriv inn en verdi for \u00e5 opprette et utvalg. Hvis raden er \x3cfont class\x3d'maxRecordInIntro'\x3euthevet\x3c/font\x3e, er maksimum antall poster overskredet.",_localized:{}}});